# frozen_string_literal: true

require "thermite/tasks"
require_relative "../lib/tasks/thermite_dir_patch"

project_dir = File.dirname(File.dirname(__FILE__))

Thermite::Tasks.new(cargo_project_path: project_dir,
                    ruby_project_path: project_dir)

task default: %w[thermite:build]
